# Generated by Django 2.2.1 on 2019-11-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_law', '0002_auto_20191019_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundlawpage',
            name='page_description',
            field=models.CharField(default='string', max_length=200),
        ),
    ]
