# Generated by Django 2.2.1 on 2019-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_description',
            field=models.CharField(default='string', max_length=200),
        ),
    ]
