# Generated by Django 2.2.1 on 2019-10-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposittaxpage',
            old_name='text',
            new_name='text_field',
        ),
    ]
