# Generated by Django 2.2.1 on 2019-10-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_guarantee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositguaranteepage',
            old_name='text',
            new_name='text_field',
        ),
    ]
