# Generated by Django 2.2.1 on 2019-11-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_guarantee', '0002_auto_20191018_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositguaranteepage',
            name='page_description',
            field=models.CharField(default='string', max_length=200),
        ),
    ]
