# Generated by Django 2.2.1 on 2019-10-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20191016_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatorpage',
            old_name='text',
            new_name='text_field',
        ),
    ]
