# Generated by Django 2.2.1 on 2019-10-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_to_fund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtofundpage',
            old_name='text',
            new_name='text_field',
        ),
    ]
