# Generated by Django 2.2.1 on 2019-10-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_bank_rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositbankratespage',
            old_name='text',
            new_name='text_field',
        ),
    ]
