# Generated by Django 2.2.1 on 2019-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_bank_rates', '0003_bankpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpage',
            name='deposit_path',
            field=models.CharField(default='string', max_length=100),
        ),
    ]
