# Generated by Django 2.2.1 on 2019-11-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_bank_rates', '0004_bankpage_deposit_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositbankratespage',
            name='page_description',
            field=models.CharField(default='string', max_length=200),
        ),
    ]
