# Generated by Django 2.2.1 on 2019-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_bank_rates', '0005_depositbankratespage_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpage',
            name='external_link',
            field=models.CharField(default='link', max_length=200),
        ),
    ]
